[package]
name = "asteroids"
version = "0.1.0"
edition = "2021"
authors = ["Alexandre Zeni"]

[dependencies]
bevy = "0.13.0"
bevy-fps-counter = "0.4.0"
lazy_static = "1.4.0"
image = "0.25.0"
winit = "0.29.15"
rand = "0.8.5"
